### ISSUE TITLE
Node upgrades

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/dacs_handbook#157]
Make sure that all of the following projects use Node 20.11.1 or higher, Node 18.19.1 or higher, or don't install node on their box. 

1. Pick a repository
2. Create a ticket in the repository and point it.
3. Reference the princeton ansible PR in the ticket. First run the playbook against staging. 
4. Deploy the application after you run the playbook.
5. If it looks ok then run it against all the environments. 

- [x] #158 - Orangelight - Max
- [x] [bibdata#2313](https://github.com/pulibrary/bibdata/issues/2313) - Max
- [x] [lib-jobs#662](https://github.com/pulibrary/lib_jobs/issues/662) - Max
- [x] [dss](https://github.com/pulibrary/DSS/pull/415) - Christina
- [x] [lockers](https://github.com/pulibrary/lockers_and_study_spaces/issues/275) - Christina
- [x] [approvals](https://github.com/pulibrary/approvals/pull/1003) - Christina
- [x] repec - Beck and Ryan
- [x] [mudd_dbs](https://github.com/pulibrary/mudd-dbs/issues/121) Christina
- [x] geaccirc - Max and Beck
- [x] library website and discovery utils (both on the same box, the library current has a [step in deployment](https://github.com/pulibrary/pul_library_drupal/blob/main/config/deploy.rb#L288) that requires node, discoveryutils doesn't need it in any capacity). If we remove the npm install and gulp deploy we need to update the readme files to note any chances to scss or js in the drupal theme need to be compiled locally and comitted to the repo prior to deploying the application. Decided to retain node in the playbook and [upgrade to 18.19.1](https://github.com/pulibrary/pul_library_drupal/issues/2040). 
- [x] [Special Collections](https://github.com/pulibrary/special_collections/issues/774) (node is no longer needed for this box, we [do not compile assets](https://github.com/pulibrary/special_collections/blob/main/config/deploy.rb#L47-L55) when the site is deployed any longer)
- [x] [friends of the library](https://github.com/pulibrary/friends_of_pul/issues/146) - jane ([App no longer needs node for deployment](https://github.com/pulibrary/friends_of_pul/blob/main/config/deploy.rb#L217)). 
- [x] [byzantine translations](https://github.com/pulibrary/byzantine_translations/issues/53) - jane
- [x] [recap](https://github.com/pulibrary/recap/issues/266) - jane
- [x] [research data](https://github.com/pulibrary/researchdata/issues/273) - jane
- [x] [pas#113](https://github.com/PrincetonUniversityLibrary/pas-craft3/issues/113)
- [x] video reserves - doesn't have node installed
- [x] marquand - doesn't have node installed
- [x] allsearch frontend
- [x] [allsearch api ](https://github.com/pulibrary/allsearch_api/issues/197)(Jane)
