### ISSUE TITLE
Deprecate mudd-dbs application

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/dacs_handbook#229]
## Task
[Mudd-dbs](https://github.com/pulibrary/mudd-dbs) has been fully migrated to static-tables to support the website migration. This application can be deprecated at this point. 

- [ ] Archive copy of the production database on GDrive alongside the static tables just in case a request comes to remove something during the first few months of new website operations. 
- [ ] Shut down mudd-dbs production environment
- [ ] Shut down mudd-dbs staging environment
- [ ] Remove mudd-dbs role and associated playbooks from princeton ansible. 
- [ ] Remove mudd-dbs as an option from ansible tower deploys
- [ ] Place the mudd-dbs github repo in deprecated/archived status.
